version: '3.7'
services:
  front:
    build:
      dockerfile: VueDevDockerFile
      context: .
    container_name: front
    ports:
      - 8080:8080
    volumes:
      - ./src:/var/www/project/src
